global using System.Net;
global using DomainUser = Domain.User.User;
global using DomainOutbox = Domain.Outbox.Outbox;
global using Domain.User;
global using Infrastructure.Data.Shared;
global using Domain.Abstractions;
global using Infrastructure.Data;
global using Infrastructure.Data.Interceptors;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Diagnostics;
global using Microsoft.Extensions.DependencyInjection;
global using Application.Config;
global using FluentValidation;
global using StackExchange.Redis;
global using Domain.Abstractions.Events;
global using System.Security.Cryptography;
global using System.Text;
global using Application.Abstractions.Email;
global using Application.Abstractions.Hashing;
global using Infrastructure.Extensions;
global using MailKit.Net.Smtp;
global using Microsoft.Extensions.Options;
global using MimeKit;