global using System.Net;
global using System.Security.Cryptography;
global using System.Text;
global using Application.Abstractions.Email;
global using Application.Abstractions.Hashing;
global using Application.Config;
global using Domain.Abstractions;
global using Domain.Abstractions.Events;
global using Domain.Products;
global using Domain.Products.ProductSkus;
global using Domain.Shared.Pagination;
global using Domain.Users;
global using FluentValidation;
global using Infrastructure.Data;
global using Infrastructure.Data.Interceptors;
global using Infrastructure.Data.Shared;
global using Infrastructure.Extensions;
global using MailKit.Net.Smtp;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Diagnostics;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Options;
global using MimeKit;
global using StackExchange.Redis;
global using DomainCart = Domain.Carts.Cart;
global using DomainDeliveryOption = Domain.DeliveryOptions.DeliveryOption;
global using DomainOrder = Domain.Orders.Order;
global using DomainProduct = Domain.Products.Product;
global using DomainPromocode = Domain.Promocodes.Promocode;
global using DomainUser = Domain.Users.User;
