// <auto-generated />
using System;
using System.Collections.Generic;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Application.Abstractions.Outbox.Outbox", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("data");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("processed_at");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_outbox");

                    b.HasIndex("ProcessedAt")
                        .HasDatabaseName("idx_outbox_processed_at_null")
                        .HasFilter("processed_at IS NULL");

                    b.ToTable("outbox", null, t =>
                        {
                            t.HasCheckConstraint("CK_type", "type IN ('email', 'file')");
                        });
                });

            modelBuilder.Entity("Domain.Brands.Brand", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_brand");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("uq_brand_name");

                    b.ToTable("brand", (string)null);
                });

            modelBuilder.Entity("Domain.Carts.Cart", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("PromocodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("promocode_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_cart");

                    b.HasIndex("PromocodeId")
                        .HasDatabaseName("ix_cart_promocode_id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("uq_cart_user");

                    b.ToTable("cart", (string)null);
                });

            modelBuilder.Entity("Domain.Categories.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_category");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("uq_category_name");

                    b.ToTable("category", (string)null);
                });

            modelBuilder.Entity("Domain.DeliveryOptions.DeliveryOption", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<long>("Price")
                        .HasColumnType("bigint")
                        .HasColumnName("price");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_delivery_options");

                    b.ToTable("delivery_options", (string)null);
                });

            modelBuilder.Entity("Domain.Orders.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DeliveryOptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("delivery_option_id");

                    b.Property<long>("DeliveryPrice")
                        .HasColumnType("bigint")
                        .HasColumnName("delivery_price");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("expires_at");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<Guid?>("PromocodeId")
                        .HasColumnType("uuid")
                        .HasColumnName("promocode_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("pending")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "BillingAddress", "Domain.Orders.Order.BillingAddress#OrderAddress", b1 =>
                        {
                            b1.Property<string>("Apartment")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("billing_address_apartment");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("billing_address_city");

                            b1.Property<string>("Home")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("billing_address_home");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("billing_address_street");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "DeliveryAddress", "Domain.Orders.Order.DeliveryAddress#OrderAddress", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Apartment")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("delivery_address_apartment");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("delivery_address_city");

                            b1.Property<string>("Home")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("delivery_address_home");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("delivery_address_street");
                        });

                    b.HasKey("Id")
                        .HasName("pk_order");

                    b.HasIndex("DeliveryOptionId")
                        .HasDatabaseName("ix_order_delivery_option_id");

                    b.HasIndex("PromocodeId")
                        .HasDatabaseName("ix_order_promocode_id");

                    b.HasIndex("UserId", "PromocodeId")
                        .IsUnique()
                        .HasDatabaseName("uq_order_user_promocode")
                        .HasFilter("    \"promocode_id\" IS NOT NULL\n    AND \"status\" <> 'cancelled'");

                    b.ToTable("order", null, t =>
                        {
                            t.HasCheckConstraint("CK_order_status", "status IN ('pending', 'paid', 'shipped', 'delivered', 'cancelled')");
                        });
                });

            modelBuilder.Entity("Domain.Products.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("BrandId")
                        .HasColumnType("uuid")
                        .HasColumnName("brand_id");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("description");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("gender");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<List<string>>("Tags")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasColumnName("tags")
                        .HasDefaultValueSql("'{}'::text[]");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_product");

                    b.HasIndex("BrandId")
                        .HasDatabaseName("ix_product_brand_id");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_product_category_id");

                    b.HasIndex("Title", "Gender", "CategoryId", "BrandId")
                        .IsUnique()
                        .HasDatabaseName("uq_product_title_gender_category_brand");

                    b.ToTable("product", null, t =>
                        {
                            t.HasCheckConstraint("CK_gender", "gender IN ('men', 'women', 'unisex')");
                        });
                });

            modelBuilder.Entity("Domain.Products.ProductSkus.ProductSku", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("color");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<int>("Size")
                        .HasColumnType("integer")
                        .HasColumnName("size");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sku");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Price", "Domain.Products.ProductSkus.ProductSku.Price#ProductSkuPrice", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<long>("Price")
                                .HasColumnType("bigint")
                                .HasColumnName("price");

                            b1.Property<long?>("SalePrice")
                                .HasColumnType("bigint")
                                .HasColumnName("sale_price");
                        });

                    b.HasKey("Id")
                        .HasName("pk_product_sku");

                    b.HasIndex("Sku")
                        .IsUnique()
                        .HasDatabaseName("uq_product_sku_sku");

                    b.HasIndex("ProductId", "Size", "Color")
                        .IsUnique()
                        .HasDatabaseName("uq_product_sku_product_size_color");

                    b.ToTable("product_sku", null, t =>
                        {
                            t.HasCheckConstraint("CK_product_sku_quantity_positive", "quantity >= 0");
                        });
                });

            modelBuilder.Entity("Domain.Products.ProductSkus.ProductSkuReviews.ProductSkuReview", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("ProductSkuId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_sku_id");

                    b.Property<int>("Rating")
                        .HasColumnType("integer")
                        .HasColumnName("rating");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("pending")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_product_sku_review");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_product_sku_review_user_id");

                    b.HasIndex("ProductSkuId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("uq_product_sku_review_product_sku_user");

                    b.ToTable("product_sku_review", null, t =>
                        {
                            t.HasCheckConstraint("CK_status", "status IN ('pending', 'rejected', 'approved')");
                        });
                });

            modelBuilder.Entity("Domain.Promocodes.Promocode", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<int>("DiscountValue")
                        .HasColumnType("integer")
                        .HasColumnName("discount_value");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.Property<int>("UsageCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("usage_count");

                    b.Property<int>("UsageLimit")
                        .HasColumnType("integer")
                        .HasColumnName("usage_limit");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "ValidityPeriod", "Domain.Promocodes.Promocode.ValidityPeriod#PromocodeValidityPeriod", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTimeOffset>("ValidFrom")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("valid_from");

                            b1.Property<DateTimeOffset>("ValidTo")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("valid_to");
                        });

                    b.HasKey("Id")
                        .HasName("pk_promocode");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("uq_promocode_code");

                    b.ToTable("promocode", null, t =>
                        {
                            t.HasCheckConstraint("CK_discount_value_percent", "type != 'percent' OR (discount_value > 0 AND discount_value < 100)");

                            t.HasCheckConstraint("CK_type", "type IN ('fixed', 'percent')");

                            t.HasCheckConstraint("CK_usage_count", "usage_count < usage_limit");

                            t.HasCheckConstraint("CK_validity_period", "valid_from < valid_to");
                        });
                });

            modelBuilder.Entity("Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<string>("FacebookId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("facebook_id");

                    b.Property<string>("FirstName")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("first_name");

                    b.Property<string>("Gender")
                        .HasColumnType("text")
                        .HasColumnName("gender");

                    b.Property<string>("GoogleId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("google_id");

                    b.Property<string>("HashedPassword")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("hashed_password");

                    b.Property<bool>("IsBanned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_banned");

                    b.Property<bool>("IsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_verified");

                    b.Property<string>("LastName")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("last_name");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("regular")
                        .HasColumnName("role");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("uq_user_email");

                    b.HasIndex("FacebookId")
                        .IsUnique()
                        .HasDatabaseName("ix_users_facebook_id");

                    b.HasIndex("GoogleId")
                        .IsUnique()
                        .HasDatabaseName("ix_users_google_id");

                    b.ToTable("users", null, t =>
                        {
                            t.HasCheckConstraint("CK_gender", "gender IN ('male', 'female', 'other')");

                            t.HasCheckConstraint("CK_role", "role IN ('regular', 'admin')");
                        });
                });

            modelBuilder.Entity("Domain.Carts.Cart", b =>
                {
                    b.HasOne("Domain.Promocodes.Promocode", "Promocode")
                        .WithMany()
                        .HasForeignKey("PromocodeId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_cart_promocode_promocode_id");

                    b.HasOne("Domain.Users.User", null)
                        .WithOne()
                        .HasForeignKey("Domain.Carts.Cart", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cart_users_user_id");

                    b.OwnsMany("Domain.Carts.CartItem", "CartItems", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<Guid>("CartId")
                                .HasColumnType("uuid")
                                .HasColumnName("cart_id");

                            b1.Property<Guid>("ProductSkuId")
                                .HasColumnType("uuid")
                                .HasColumnName("product_sku_id");

                            b1.Property<int>("Quantity")
                                .HasColumnType("integer")
                                .HasColumnName("quantity");

                            b1.HasKey("Id")
                                .HasName("pk_cart_item");

                            b1.HasIndex("ProductSkuId")
                                .HasDatabaseName("ix_cart_item_product_sku_id");

                            b1.HasIndex("CartId", "ProductSkuId")
                                .IsUnique()
                                .HasDatabaseName("uq_cart_items_cart_id_product_sku_id");

                            b1.ToTable("cart_item", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("CartId")
                                .HasConstraintName("fk_cart_item_cart_cart_id");

                            b1.HasOne("Domain.Products.ProductSkus.ProductSku", "ProductSku")
                                .WithMany()
                                .HasForeignKey("ProductSkuId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired()
                                .HasConstraintName("fk_cart_item_product_sku_product_sku_id");

                            b1.Navigation("ProductSku");
                        });

                    b.Navigation("CartItems");

                    b.Navigation("Promocode");
                });

            modelBuilder.Entity("Domain.Orders.Order", b =>
                {
                    b.HasOne("Domain.DeliveryOptions.DeliveryOption", "DeliveryOption")
                        .WithMany()
                        .HasForeignKey("DeliveryOptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_order_delivery_options_delivery_option_id");

                    b.HasOne("Domain.Promocodes.Promocode", "Promocode")
                        .WithMany()
                        .HasForeignKey("PromocodeId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_order_promocode_promocode_id");

                    b.HasOne("Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_users_user_id");

                    b.OwnsMany("Domain.Orders.OrderItem", "OrderItems", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<Guid>("OrderId")
                                .HasColumnType("uuid")
                                .HasColumnName("order_id");

                            b1.Property<long>("Price")
                                .HasColumnType("bigint")
                                .HasColumnName("price");

                            b1.Property<Guid>("ProductSkuId")
                                .HasColumnType("uuid")
                                .HasColumnName("product_sku_id");

                            b1.Property<int>("Quantity")
                                .HasColumnType("integer")
                                .HasColumnName("quantity");

                            b1.HasKey("Id")
                                .HasName("pk_order_item");

                            b1.HasIndex("ProductSkuId")
                                .HasDatabaseName("ix_order_item_product_sku_id");

                            b1.HasIndex("OrderId", "ProductSkuId")
                                .IsUnique()
                                .HasDatabaseName("uq_order_items_order_id_product_sku_id");

                            b1.ToTable("order_item", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("OrderId")
                                .HasConstraintName("fk_order_item_order_order_id");

                            b1.HasOne("Domain.Products.ProductSkus.ProductSku", "ProductSku")
                                .WithMany()
                                .HasForeignKey("ProductSkuId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired()
                                .HasConstraintName("fk_order_item_product_sku_product_sku_id");

                            b1.Navigation("ProductSku");
                        });

                    b.OwnsMany("Domain.Orders.OrderPayment", "OrderPayments", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<long>("Amount")
                                .HasColumnType("bigint")
                                .HasColumnName("amount");

                            b1.Property<DateTimeOffset>("CreatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("created_at");

                            b1.Property<Guid>("OrderId")
                                .HasColumnType("uuid")
                                .HasColumnName("order_id");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .ValueGeneratedOnAdd()
                                .HasColumnType("text")
                                .HasDefaultValue("pending")
                                .HasColumnName("status");

                            b1.Property<string>("TransactionId")
                                .IsRequired()
                                .HasMaxLength(60)
                                .HasColumnType("character varying(60)")
                                .HasColumnName("transaction_id");

                            b1.Property<DateTimeOffset>("UpdatedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("updated_at");

                            b1.HasKey("Id")
                                .HasName("pk_order_payment");

                            b1.HasIndex("OrderId")
                                .HasDatabaseName("ix_order_payment_order_id");

                            b1.HasIndex("TransactionId")
                                .IsUnique()
                                .HasDatabaseName("ix_order_payment_transaction_id");

                            b1.ToTable("order_payment", null, t =>
                                {
                                    t.HasCheckConstraint("CK_order_payment_status", "status IN ('pending', 'completed', 'failed', 'expired', 'refunded', 'cancelled')");
                                });

                            b1.WithOwner()
                                .HasForeignKey("OrderId")
                                .HasConstraintName("fk_order_payment_order_order_id");
                        });

                    b.Navigation("DeliveryOption");

                    b.Navigation("OrderItems");

                    b.Navigation("OrderPayments");

                    b.Navigation("Promocode");
                });

            modelBuilder.Entity("Domain.Products.Product", b =>
                {
                    b.HasOne("Domain.Brands.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_product_brand_brand_id");

                    b.HasOne("Domain.Categories.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_product_category_category_id");

                    b.Navigation("Brand");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Domain.Products.ProductSkus.ProductSku", b =>
                {
                    b.HasOne("Domain.Products.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_sku_product_product_id");

                    b.OwnsMany("Domain.Products.ProductSkus.ProductSkuImage", "Images", b1 =>
                        {
                            b1.Property<Guid>("ProductSkuId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<Guid>("Id");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(100);

                            b1.Property<string>("Url")
                                .IsRequired()
                                .HasMaxLength(200);

                            b1.HasKey("ProductSkuId", "__synthesizedOrdinal");

                            b1.ToTable("product_sku");

                            b1
                                .ToJson("images")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("ProductSkuId")
                                .HasConstraintName("fk_product_sku_product_sku_product_sku_id");
                        });

                    b.Navigation("Images");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Domain.Products.ProductSkus.ProductSkuReviews.ProductSkuReview", b =>
                {
                    b.HasOne("Domain.Products.ProductSkus.ProductSku", null)
                        .WithMany("Reviews")
                        .HasForeignKey("ProductSkuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_sku_review_product_sku_product_sku_id");

                    b.HasOne("Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_sku_review_users_user_id");

                    b.OwnsMany("Domain.Products.ProductSkus.ProductSkuReviews.ProductSkuReviewImage", "Images", b1 =>
                        {
                            b1.Property<Guid>("ProductSkuReviewId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<Guid>("Id");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(100);

                            b1.Property<string>("Url")
                                .IsRequired()
                                .HasMaxLength(200);

                            b1.HasKey("ProductSkuReviewId", "__synthesizedOrdinal");

                            b1.ToTable("product_sku_review");

                            b1
                                .ToJson("images")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("ProductSkuReviewId")
                                .HasConstraintName("fk_product_sku_review_product_sku_review_product_sku_review_id");
                        });

                    b.Navigation("Images");
                });

            modelBuilder.Entity("Domain.Products.ProductSkus.ProductSku", b =>
                {
                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
