services:
  api:
    image: api
    container_name: kicks-api
    build:
      context: .
    restart: unless-stopped
    ports:
      - "4000:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      OTEL_SERVICE_NAME: Kicks.Api
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
      OTEL_EXPORTER_OTLP_PROTOCOL: grpc

      Application__ClientUrl: ${CLIENT_URL}
      Application__SessionCookieName: ${SESSION_COOKIE_NAME}
      Application__OAuthStateCookieName: ${OAUTH_STATE_COOKIE_NAME}
      Application__CookieSecure: ${COOKIE_SECURE}
      Application__MaxCancelledOrdersPerDay: ${MAX_CANCELLED_ORDERS_PER_DAY}
      Application__AccountVerificationPath: ${ACCOUNT_VERIFICATION_PATH}
      Application__ResetPasswordPath: ${RESET_PASSWORD_PATH}
      Application__AccountVerificationTtlMinutes: ${ACCOUNT_VERIFICATION_TTL_MINUTES}
      Application__SessionTtlMinutes: ${SESSION_TTL_MINUTES}
      Application__OAUthStateTtlMinutes: ${OAUTH_STATE_TTL_MINUTES}
      Application__ResetPasswordTtlMinutes: ${RESET_PASSWORD_TTL_MINUTES}
      Application__OrderExpirationTtlMinutes: ${ORDER_EXPIRATION_TTL_MINUTES}


      OAuth__Google__ClientId: ${OAUTH_GOOGLE_CLIENT_ID}
      OAuth__Google__ClientSecret: ${OAUTH_GOOGLE_CLIENT_SECRET}
      OAuth__Google__RedirectUrl: ${OAUTH_GOOGLE_REDIRECT_URL}
      OAuth__Facebook__ClientId: ${OAUTH_FACEBOOK_CLIENT_ID}
      OAuth__Facebook__ClientSecret: ${OAUTH_FACEBOOK_CLIENT_SECRET}
      OAuth__Facebook__RedirectUrl: ${OAUTH_FACEBOOK_REDIRECT_URL}

      Database__Host: postgres
      Database__Port: ${DATABASE_PORT}
      Database__User: ${DATABASE_USER}
      Database__Password: ${DATABASE_PASSWORD}
      Database__Name: ${DATABASE_NAME}
      Database__Ssl: ${DATABASE_SSL}

      Redis__Host: redis
      Redis__Port: ${REDIS_PORT}
      Redis__User: ${REDIS_USER}
      Redis__Password: ${REDIS_PASSWORD}
      Redis__Database: ${REDIS_DB}

      Smtp__Host: mailpit
      Smtp__Port: 1025
      Smtp__User: ${SMTP_USER}
      Smtp__Password: ${SMTP_PASSWORD}
      Smtp__From: ${SMTP_FROM}

      Cloudinary__ApiKey: ${CLOUDINARY_API_KEY}
      Cloudinary__Secret: ${CLOUDINARY_SECRET}
      Cloudinary__CloudName: ${CLOUDINARY_CLOUD_NAME}
      Cloudinary__Folder: ${CLOUDINARY_FOLDER}

      Stripe__Secret: ${STRIPE_SECRET}

      RateLimit__SignUp: ${RATELIMIT_SIGN_UP}
      RateLimit__SignIn: ${RATELIMIT_SIGN_IN}
      RateLimit__VerifyAccount: ${RATELIMIT_VERIFY_ACCOUNT}
      RateLimit__GetProfile: ${RATELIMIT_GET_PROFILE}
      RateLimit__ForgotPassword: ${RATELIMIT_FORGOT_PASSWORD}
      RateLimit__ResetPassword: ${RATELIMIT_RESET_PASSWORD}
      RateLimit__Logout: ${RATELIMIT_LOGOUT}
      RateLimit__GetProductSku: ${RATELIMIT_GET_PRODUCT_SKU}
      RateLimit__GetProductSkus: ${RATELIMIT_GET_PRODUCT_SKUS}
      RateLimit__GetProductSkusFilters: ${RATELIMIT_GET_PRODUCT_SKUS_FILTERS}
      RateLimit__GetCart: ${RATELIMIT_GET_CART}
      RateLimit__AddCartItem: ${RATELIMIT_ADD_CART_ITEM}
      RateLimit__UpdateCartItemQuantity: ${RATELIMIT_UPDATE_CART_ITEM_QUANTITY}
      RateLimit__RemoveCartItem: ${RATELIMIT_REMOVE_CART_ITEM}
      RateLimit__ClearCart: ${RATELIMIT_CLEAR_CART}
      RateLimit__ApplyPromocode: ${RATELIMIT_APPLY_PROMOCODE}
      RateLimit__RemovePromocode: ${RATELIMIT_REMOVE_PROMOCODE}
      RateLimit__CreateOrder: ${RATELIMIT_CREATE_ORDER}
      RateLimit__GetOrders: ${RATELIMIT_GET_ORDERS}
      RateLimit__GetOrder: ${RATELIMIT_GET_ORDER}
      RateLimit__GetDeliveryOptions: ${RATELIMIT_GET_DELIVERY_OPTIONS}

    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      seq:
        condition: service_started

  postgres:
    image: postgres:18-alpine
    container_name: kicks-postgres
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - kicks-postgres-data:/var/lib/postgresql
    ports:
      - "5433:5432"
    healthcheck:
      test:
        [ "CMD-SHELL", "pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:8-alpine
    container_name: kicks-redis
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - kicks-redis-data:/data
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli -a ${REDIS_PASSWORD} ping" ]
      interval: 5s
      timeout: 3s
      retries: 5
    ports:
      - "6380:6379"

  seq:
    image: datalust/seq:latest
    container_name: kicks-seq
    restart: unless-stopped
    environment:
      ACCEPT_EULA: "Y"
      SEQ_FIRSTRUN_ADMINPASSWORD: "password"
    ports:
      - "8081:80"
    volumes:
      - kicks-seq-data:/data

  otel-collector:
    image: otel/opentelemetry-collector:latest
    container_name: kicks-otel-collector
    command: ["--config=/etc/otel-collector.yaml"]
    volumes:
      - ./otel-collector.yaml:/etc/otel-collector.yaml
    ports:
      - "4317:4317"
      - "9464:9464"
    depends_on:
      - jaeger
      - prometheus

  prometheus:
    image: prom/prometheus:v3.5.4
    container_name: kicks-prometheus
    ports:
      - "9090:9090"
    volumes:
    - kicks-prometheus-data:/prometheus

  jaeger:
    image: jaegertracing/all-in-one:1.76.0
    container_name: kicks-jaeger
    ports:
      - "16686:16686"
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://localhost:16686/" ]
      interval: 10s
      timeout: 5s
      retries: 5

  node_exporter:
      image: quay.io/prometheus/node-exporter:latest
      container_name: kicks-node-exporter
      command:
        - '--path.rootfs=/host'
      pid: host
      restart: unless-stopped
      volumes:
        - '/:/host:ro,rslave'
  mailpit:
    image: axllent/mailpit:v1.27.4
    container_name: kicks-mailpit
    restart: unless-stopped
    command:
      - --smtp-auth-allow-insecure
    volumes:
      - /opt/fakemail-data:/data
    environment:
      MP_UI_AUTH: "admin:admin123"
      MP_SMTP_AUTH: "${SMTP_USER}:${SMTP_PASSWORD}"
    ports:
      - 8025:8025
      - 1025:1025

volumes:
  kicks-postgres-data:
  kicks-redis-data:
  kicks-seq-data:
  kicks-prometheus-data:
